

spring:
  application:
    name: department-service
  config:
    import: "optional:configserver:http://localhost/8088"
server:
  port: 8081
management:
  tracing:
    sampling:
      probability: 1.0

